# Whether vault compatibility is enabled
enable-vault: true
# Whether the item rarity description will be italic
italic-item-rarity: true
# Whether items have a cooldown animation
enable-cooldown-animation: true
# Whether the sidebar is enabled
enable-sidebar: false