# ----------------------------------------MAIN----------------------------------------

# Whether vault compatibility is enabled
enable-vault: true

# Whether warnings about an optional dependency not being installed are ignored
disable-dependency-warnings: false

# ----------------------------------------UI----------------------------------------

# Whether items have a cooldown animation
enable-cooldown-animation: true

# Whether the sidebar is enabled
# It's a discontinued legacy feature.
enable-sidebar: false
sidebar-location-display: Hub

# Whether the player is sent an actionbar upon receiving exp
send-exp-actionbar: true

# Item rarity description formatting
italic-item-rarity: false
bold-item-rarity: false
capitalised-item-rarity: false
white-common-item-rarity: false

# The default item rarity.
# Choose from: Standard, Common, Uncommon, Rare, Exotic, Epic, Legendary, Mythic.
# Custom registration will come soon
# Standard will not show as a description below the item name

default-custom-item-rarity: STANDARD
vanilla-item-rarity: STANDARD
vanilla-item-overrides:
# Example:
# vanilla-item-overrides:
#   diamond: uncommon
#   diamond_sword: uncommon
#   ender_pearl: rare
vanilla-item-subcategories:
# Example:
# vanilla-item-subcategories:
# diamond_sword: sword
# diamond_axe: axe
# bow: bow

# ----------------------------------------CONSTANTS----------------------------------------

# The armour protection constant (n)
# Effective HP = HP(1+Defence/n)
armour-constant: 16

# ----------------------------------------CURRENCY----------------------------------------

# Singular and plural form of the currency name
# Support mini-message
currency-singular: Credit
currency-plural: Credits

# Uses "named text colour"
currency-colour: Green

# ----------------------------------------CRAFTING----------------------------------------

# Controls what crafting stations the un-smelting recipes are added to
# Un-smelting recipes are specified in item creation
add-unsmelting-recipes-to-furnace: false
add-unsmelting-recipes-to-smoker: false
add-unsmelting-recipes-to-blast-furnace: true
add-unsmelting-recipes-to-campfire: false

