# ----------------------------------------MAIN----------------------------------------

# Whether vault compatibility is enabled
enable-vault: true

# Whether warnings about an optional dependency not being installed are ignored
disable-dependency-warnings: false

# ----------------------------------------UI----------------------------------------

# Whether items have a cooldown animation
enable-cooldown-animation: true

# Whether the sidebar is enabled
enable-sidebar: false

# Whether the player is sent an actionbar upon receiving exp
send-exp-actionbar: true

# Whether the item rarity description will be italic
italic-item-rarity: true

# ----------------------------------------CURRENCY----------------------------------------

# Singular and plural form of the currency name
currency-singular: Credit
currency-plural: Credits

# ----------------------------------------CRAFTING----------------------------------------

# Controls what crafting stations the un-smelting recipes are added to
# Un-smelting recipes are specified in item creation
add-unsmelting-recipes-to-furnace: false
add-unsmelting-recipes-to-smoker: false
add-unsmelting-recipes-to-blast-furnace: true
add-unsmelting-recipes-to-campfire: false

